(cl:defpackage authoring_msgs-msg
  (:use )
  (:export
   "<ACTION>"
   "ACTION"
   "<AUTHORINGACTION>"
   "AUTHORINGACTION"
   "<AUTHORINGACTIONFEEDBACK>"
   "AUTHORINGACTIONFEEDBACK"
   "<AUTHORINGACTIONGOAL>"
   "AUTHORINGACTIONGOAL"
   "<AUTHORINGACTIONRESULT>"
   "AUTHORINGACTIONRESULT"
   "<AUTHORINGFEEDBACK>"
   "AUTHORINGFEEDBACK"
   "<AUTHORINGGOAL>"
   "AUTHORINGGOAL"
   "<AUTHORINGRESULT>"
   "AUTHORINGRESULT"
   "<COMMAND>"
   "COMMAND"
   "<POI>"
   "POI"
   "<POIARRAY>"
   "POIARRAY"
  ))

