; Auto-generated. Do not edit!


(cl:in-package authoring_msgs-msg)


;//! \htmlinclude AuthoringFeedback.msg.html

(cl:defclass <AuthoringFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass AuthoringFeedback (<AuthoringFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AuthoringFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AuthoringFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name authoring_msgs-msg:<AuthoringFeedback> is deprecated: use authoring_msgs-msg:AuthoringFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <AuthoringFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader authoring_msgs-msg:progress-val is deprecated.  Use authoring_msgs-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AuthoringFeedback>) ostream)
  "Serializes a message object of type '<AuthoringFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'progress))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'progress))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AuthoringFeedback>) istream)
  "Deserializes a message object of type '<AuthoringFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'progress) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'progress)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AuthoringFeedback>)))
  "Returns string type for a message object of type '<AuthoringFeedback>"
  "authoring_msgs/AuthoringFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AuthoringFeedback)))
  "Returns string type for a message object of type 'AuthoringFeedback"
  "authoring_msgs/AuthoringFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AuthoringFeedback>)))
  "Returns md5sum for a message object of type '<AuthoringFeedback>"
  "dba61511a16def70687d596d0b9ef8c5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AuthoringFeedback)))
  "Returns md5sum for a message object of type 'AuthoringFeedback"
  "dba61511a16def70687d596d0b9ef8c5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AuthoringFeedback>)))
  "Returns full string definition for message of type '<AuthoringFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32[] progress~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AuthoringFeedback)))
  "Returns full string definition for message of type 'AuthoringFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32[] progress~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AuthoringFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'progress) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AuthoringFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'AuthoringFeedback
    (cl:cons ':progress (progress msg))
))
