; Auto-generated. Do not edit!


(cl:in-package authoring_msgs-msg)


;//! \htmlinclude AuthoringResult.msg.html

(cl:defclass <AuthoringResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type std_msgs-msg:Bool
    :initform (cl:make-instance 'std_msgs-msg:Bool)))
)

(cl:defclass AuthoringResult (<AuthoringResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AuthoringResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AuthoringResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name authoring_msgs-msg:<AuthoringResult> is deprecated: use authoring_msgs-msg:AuthoringResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <AuthoringResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader authoring_msgs-msg:success-val is deprecated.  Use authoring_msgs-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AuthoringResult>) ostream)
  "Serializes a message object of type '<AuthoringResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'success) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AuthoringResult>) istream)
  "Deserializes a message object of type '<AuthoringResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'success) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AuthoringResult>)))
  "Returns string type for a message object of type '<AuthoringResult>"
  "authoring_msgs/AuthoringResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AuthoringResult)))
  "Returns string type for a message object of type 'AuthoringResult"
  "authoring_msgs/AuthoringResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AuthoringResult>)))
  "Returns md5sum for a message object of type '<AuthoringResult>"
  "5f31cb2e813cfb0e488c574c3b5d9dbe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AuthoringResult)))
  "Returns md5sum for a message object of type 'AuthoringResult"
  "5f31cb2e813cfb0e488c574c3b5d9dbe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AuthoringResult>)))
  "Returns full string definition for message of type '<AuthoringResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/Bool success~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AuthoringResult)))
  "Returns full string definition for message of type 'AuthoringResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/Bool success~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AuthoringResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'success))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AuthoringResult>))
  "Converts a ROS message object to a list"
  (cl:list 'AuthoringResult
    (cl:cons ':success (success msg))
))
