// Generated by gencpp from file authoring_msgs/AuthoringFeedback.msg
// DO NOT EDIT!


#ifndef AUTHORING_MSGS_MESSAGE_AUTHORINGFEEDBACK_H
#define AUTHORING_MSGS_MESSAGE_AUTHORINGFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace authoring_msgs
{
template <class ContainerAllocator>
struct AuthoringFeedback_
{
  typedef AuthoringFeedback_<ContainerAllocator> Type;

  AuthoringFeedback_()
    : progress()  {
    }
  AuthoringFeedback_(const ContainerAllocator& _alloc)
    : progress(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _progress_type;
  _progress_type progress;





  typedef boost::shared_ptr< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct AuthoringFeedback_

typedef ::authoring_msgs::AuthoringFeedback_<std::allocator<void> > AuthoringFeedback;

typedef boost::shared_ptr< ::authoring_msgs::AuthoringFeedback > AuthoringFeedbackPtr;
typedef boost::shared_ptr< ::authoring_msgs::AuthoringFeedback const> AuthoringFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::authoring_msgs::AuthoringFeedback_<ContainerAllocator1> & lhs, const ::authoring_msgs::AuthoringFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.progress == rhs.progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::authoring_msgs::AuthoringFeedback_<ContainerAllocator1> & lhs, const ::authoring_msgs::AuthoringFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace authoring_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dba61511a16def70687d596d0b9ef8c5";
  }

  static const char* value(const ::authoring_msgs::AuthoringFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdba61511a16def70ULL;
  static const uint64_t static_value2 = 0x687d596d0b9ef8c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "authoring_msgs/AuthoringFeedback";
  }

  static const char* value(const ::authoring_msgs::AuthoringFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int32[] progress\n"
"\n"
;
  }

  static const char* value(const ::authoring_msgs::AuthoringFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AuthoringFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::authoring_msgs::AuthoringFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::authoring_msgs::AuthoringFeedback_<ContainerAllocator>& v)
  {
    s << indent << "progress[]" << std::endl;
    for (size_t i = 0; i < v.progress.size(); ++i)
    {
      s << indent << "  progress[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.progress[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTHORING_MSGS_MESSAGE_AUTHORINGFEEDBACK_H
