// Generated by gencpp from file authoring_msgs/AuthoringAction.msg
// DO NOT EDIT!


#ifndef AUTHORING_MSGS_MESSAGE_AUTHORINGACTION_H
#define AUTHORING_MSGS_MESSAGE_AUTHORINGACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <authoring_msgs/AuthoringActionGoal.h>
#include <authoring_msgs/AuthoringActionResult.h>
#include <authoring_msgs/AuthoringActionFeedback.h>

namespace authoring_msgs
{
template <class ContainerAllocator>
struct AuthoringAction_
{
  typedef AuthoringAction_<ContainerAllocator> Type;

  AuthoringAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  AuthoringAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::authoring_msgs::AuthoringActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::authoring_msgs::AuthoringActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::authoring_msgs::AuthoringActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::authoring_msgs::AuthoringAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::authoring_msgs::AuthoringAction_<ContainerAllocator> const> ConstPtr;

}; // struct AuthoringAction_

typedef ::authoring_msgs::AuthoringAction_<std::allocator<void> > AuthoringAction;

typedef boost::shared_ptr< ::authoring_msgs::AuthoringAction > AuthoringActionPtr;
typedef boost::shared_ptr< ::authoring_msgs::AuthoringAction const> AuthoringActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::authoring_msgs::AuthoringAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::authoring_msgs::AuthoringAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::authoring_msgs::AuthoringAction_<ContainerAllocator1> & lhs, const ::authoring_msgs::AuthoringAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::authoring_msgs::AuthoringAction_<ContainerAllocator1> & lhs, const ::authoring_msgs::AuthoringAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace authoring_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::authoring_msgs::AuthoringAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::authoring_msgs::AuthoringAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::authoring_msgs::AuthoringAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::authoring_msgs::AuthoringAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::authoring_msgs::AuthoringAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::authoring_msgs::AuthoringAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::authoring_msgs::AuthoringAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77d42cd79ed7af67d7aec4191f656d1c";
  }

  static const char* value(const ::authoring_msgs::AuthoringAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77d42cd79ed7af67ULL;
  static const uint64_t static_value2 = 0xd7aec4191f656d1cULL;
};

template<class ContainerAllocator>
struct DataType< ::authoring_msgs::AuthoringAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "authoring_msgs/AuthoringAction";
  }

  static const char* value(const ::authoring_msgs::AuthoringAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::authoring_msgs::AuthoringAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"AuthoringActionGoal action_goal\n"
"AuthoringActionResult action_result\n"
"AuthoringActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: authoring_msgs/AuthoringActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"AuthoringGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: authoring_msgs/AuthoringGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"authoring_msgs/Action goal\n"
"\n"
"================================================================================\n"
"MSG: authoring_msgs/Action\n"
"#Types\n"
"uint8 PICK=0\n"
"uint8 SCREW=1\n"
"uint8 PLACE=2\n"
"uint8 WIPE=3\n"
"uint8 MOVE_OBJECT=4\n"
"uint8 RESET=5\n"
"uint8 MOVE=6\n"
"uint8 MOVE_TO_CONTACT=7\n"
"uint8 GRASP=8\n"
"uint8 RELEASE=9\n"
"uint8 VIEW=10\n"
"uint8 INSPECT=11\n"
"uint8 WAIT=12\n"
"uint8 PUSH=13\n"
"uint8 STOP=14\n"
"uint8 INSERT=15\n"
"uint8 MOVE_FORCE=16\n"
"uint8 UNSCREW=17\n"
"uint8 MOVE_ANGLE=18\n"
"uint8 PULL=19\n"
"uint8 CAMERA_VELOCITY=20\n"
"uint8 MOVE_UNKNOWN=21\n"
"uint8 PULL_DRAWER=22\n"
"uint8 BIAS_FORCES=23\n"
"uint8 DROP=24\n"
"uint8 RELEASE_FORCE=25\n"
"\n"
"# Type\n"
"uint8 type\n"
"\n"
"std_msgs/Bool sim\n"
"\n"
"std_msgs/Bool finished\n"
"\n"
"# HybridPoseArray (for high level planning)\n"
"panda_ros_msgs/HybridPoseArray poses\n"
"\n"
"# HybridPose (for low level planning)\n"
"panda_ros_msgs/HybridPose pose\n"
"\n"
"# JointState (for going to fixed position, example reset)\n"
"float64[] joint_pose\n"
"\n"
"# Item\n"
"std_msgs/String item\n"
"\n"
"# Velocity\n"
"geometry_msgs/Twist velocity\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
"================================================================================\n"
"MSG: panda_ros_msgs/HybridPoseArray\n"
"Header header\n"
"panda_ros_msgs/HybridPose[] poses\n"
"\n"
"================================================================================\n"
"MSG: panda_ros_msgs/HybridPose\n"
"# Pose\n"
"geometry_msgs/Pose pose\n"
"\n"
"# Selection vector [6 (drop rotation for now)]\n"
"uint8[] sel_vector\n"
"\n"
"# Desired Wrench\n"
"geometry_msgs/Wrench wrench\n"
"\n"
"# Constraint Frame (might drop)\n"
"geometry_msgs/Quaternion constraint_frame\n"
"\n"
"# Header\n"
"Header header\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Wrench\n"
"# This represents force in free space, separated into\n"
"# its linear and angular parts.\n"
"Vector3  force\n"
"Vector3  torque\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: authoring_msgs/AuthoringActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"AuthoringResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: authoring_msgs/AuthoringResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"std_msgs/Bool success\n"
"\n"
"================================================================================\n"
"MSG: authoring_msgs/AuthoringActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"AuthoringFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: authoring_msgs/AuthoringFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int32[] progress\n"
"\n"
;
  }

  static const char* value(const ::authoring_msgs::AuthoringAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::authoring_msgs::AuthoringAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AuthoringAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::authoring_msgs::AuthoringAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::authoring_msgs::AuthoringAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::authoring_msgs::AuthoringActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::authoring_msgs::AuthoringActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::authoring_msgs::AuthoringActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTHORING_MSGS_MESSAGE_AUTHORINGACTION_H
