// Generated by gencpp from file authoring_msgs/AuthoringResult.msg
// DO NOT EDIT!


#ifndef AUTHORING_MSGS_MESSAGE_AUTHORINGRESULT_H
#define AUTHORING_MSGS_MESSAGE_AUTHORINGRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace authoring_msgs
{
template <class ContainerAllocator>
struct AuthoringResult_
{
  typedef AuthoringResult_<ContainerAllocator> Type;

  AuthoringResult_()
    : success()  {
    }
  AuthoringResult_(const ContainerAllocator& _alloc)
    : success(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::authoring_msgs::AuthoringResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::authoring_msgs::AuthoringResult_<ContainerAllocator> const> ConstPtr;

}; // struct AuthoringResult_

typedef ::authoring_msgs::AuthoringResult_<std::allocator<void> > AuthoringResult;

typedef boost::shared_ptr< ::authoring_msgs::AuthoringResult > AuthoringResultPtr;
typedef boost::shared_ptr< ::authoring_msgs::AuthoringResult const> AuthoringResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::authoring_msgs::AuthoringResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::authoring_msgs::AuthoringResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::authoring_msgs::AuthoringResult_<ContainerAllocator1> & lhs, const ::authoring_msgs::AuthoringResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::authoring_msgs::AuthoringResult_<ContainerAllocator1> & lhs, const ::authoring_msgs::AuthoringResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace authoring_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::authoring_msgs::AuthoringResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::authoring_msgs::AuthoringResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::authoring_msgs::AuthoringResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::authoring_msgs::AuthoringResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::authoring_msgs::AuthoringResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::authoring_msgs::AuthoringResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::authoring_msgs::AuthoringResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f31cb2e813cfb0e488c574c3b5d9dbe";
  }

  static const char* value(const ::authoring_msgs::AuthoringResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f31cb2e813cfb0eULL;
  static const uint64_t static_value2 = 0x488c574c3b5d9dbeULL;
};

template<class ContainerAllocator>
struct DataType< ::authoring_msgs::AuthoringResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "authoring_msgs/AuthoringResult";
  }

  static const char* value(const ::authoring_msgs::AuthoringResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::authoring_msgs::AuthoringResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"std_msgs/Bool success\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::authoring_msgs::AuthoringResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::authoring_msgs::AuthoringResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AuthoringResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::authoring_msgs::AuthoringResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::authoring_msgs::AuthoringResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTHORING_MSGS_MESSAGE_AUTHORINGRESULT_H
