// Generated by gencpp from file authoring_msgs/POI.msg
// DO NOT EDIT!


#ifndef AUTHORING_MSGS_MESSAGE_POI_H
#define AUTHORING_MSGS_MESSAGE_POI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <std_msgs/String.h>
#include <geometry_msgs/PoseStamped.h>

namespace authoring_msgs
{
template <class ContainerAllocator>
struct POI_
{
  typedef POI_<ContainerAllocator> Type;

  POI_()
    : type()
    , id(0)
    , state()
    , age(0)
    , pose()  {
    }
  POI_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , id(0)
    , state(_alloc)
    , age(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _type_type;
  _type_type type;

   typedef uint8_t _id_type;
  _id_type id;

   typedef  ::std_msgs::String_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef uint8_t _age_type;
  _age_type age;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::authoring_msgs::POI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::authoring_msgs::POI_<ContainerAllocator> const> ConstPtr;

}; // struct POI_

typedef ::authoring_msgs::POI_<std::allocator<void> > POI;

typedef boost::shared_ptr< ::authoring_msgs::POI > POIPtr;
typedef boost::shared_ptr< ::authoring_msgs::POI const> POIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::authoring_msgs::POI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::authoring_msgs::POI_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::authoring_msgs::POI_<ContainerAllocator1> & lhs, const ::authoring_msgs::POI_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.id == rhs.id &&
    lhs.state == rhs.state &&
    lhs.age == rhs.age &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::authoring_msgs::POI_<ContainerAllocator1> & lhs, const ::authoring_msgs::POI_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace authoring_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::authoring_msgs::POI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::authoring_msgs::POI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::authoring_msgs::POI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::authoring_msgs::POI_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::authoring_msgs::POI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::authoring_msgs::POI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::authoring_msgs::POI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4537f0ac14a21e77b6975b4bbfc9188a";
  }

  static const char* value(const ::authoring_msgs::POI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4537f0ac14a21e77ULL;
  static const uint64_t static_value2 = 0xb6975b4bbfc9188aULL;
};

template<class ContainerAllocator>
struct DataType< ::authoring_msgs::POI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "authoring_msgs/POI";
  }

  static const char* value(const ::authoring_msgs::POI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::authoring_msgs::POI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Type\n"
"std_msgs/String type\n"
"\n"
"# ID\n"
"uint8 id\n"
"\n"
"# State\n"
"std_msgs/String state\n"
"\n"
"# Age\n"
"uint8 age\n"
"\n"
"# PoseStamped\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::authoring_msgs::POI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::authoring_msgs::POI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.id);
      stream.next(m.state);
      stream.next(m.age);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct POI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::authoring_msgs::POI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::authoring_msgs::POI_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTHORING_MSGS_MESSAGE_POI_H
