// Generated by gencpp from file authoring_msgs/POIArray.msg
// DO NOT EDIT!


#ifndef AUTHORING_MSGS_MESSAGE_POIARRAY_H
#define AUTHORING_MSGS_MESSAGE_POIARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <authoring_msgs/POI.h>

namespace authoring_msgs
{
template <class ContainerAllocator>
struct POIArray_
{
  typedef POIArray_<ContainerAllocator> Type;

  POIArray_()
    : poi_array()  {
    }
  POIArray_(const ContainerAllocator& _alloc)
    : poi_array(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::authoring_msgs::POI_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::authoring_msgs::POI_<ContainerAllocator> >> _poi_array_type;
  _poi_array_type poi_array;





  typedef boost::shared_ptr< ::authoring_msgs::POIArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::authoring_msgs::POIArray_<ContainerAllocator> const> ConstPtr;

}; // struct POIArray_

typedef ::authoring_msgs::POIArray_<std::allocator<void> > POIArray;

typedef boost::shared_ptr< ::authoring_msgs::POIArray > POIArrayPtr;
typedef boost::shared_ptr< ::authoring_msgs::POIArray const> POIArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::authoring_msgs::POIArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::authoring_msgs::POIArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::authoring_msgs::POIArray_<ContainerAllocator1> & lhs, const ::authoring_msgs::POIArray_<ContainerAllocator2> & rhs)
{
  return lhs.poi_array == rhs.poi_array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::authoring_msgs::POIArray_<ContainerAllocator1> & lhs, const ::authoring_msgs::POIArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace authoring_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::authoring_msgs::POIArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::authoring_msgs::POIArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::authoring_msgs::POIArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::authoring_msgs::POIArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::authoring_msgs::POIArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::authoring_msgs::POIArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::authoring_msgs::POIArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "705692ced92474947d1df89af3eb8c54";
  }

  static const char* value(const ::authoring_msgs::POIArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x705692ced9247494ULL;
  static const uint64_t static_value2 = 0x7d1df89af3eb8c54ULL;
};

template<class ContainerAllocator>
struct DataType< ::authoring_msgs::POIArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "authoring_msgs/POIArray";
  }

  static const char* value(const ::authoring_msgs::POIArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::authoring_msgs::POIArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# POIs\n"
"authoring_msgs/POI[] poi_array\n"
"\n"
"================================================================================\n"
"MSG: authoring_msgs/POI\n"
"# Type\n"
"std_msgs/String type\n"
"\n"
"# ID\n"
"uint8 id\n"
"\n"
"# State\n"
"std_msgs/String state\n"
"\n"
"# Age\n"
"uint8 age\n"
"\n"
"# PoseStamped\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::authoring_msgs::POIArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::authoring_msgs::POIArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poi_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct POIArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::authoring_msgs::POIArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::authoring_msgs::POIArray_<ContainerAllocator>& v)
  {
    s << indent << "poi_array[]" << std::endl;
    for (size_t i = 0; i < v.poi_array.size(); ++i)
    {
      s << indent << "  poi_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::authoring_msgs::POI_<ContainerAllocator> >::stream(s, indent + "    ", v.poi_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTHORING_MSGS_MESSAGE_POIARRAY_H
