// Auto-generated. Do not edit!

// (in-package authoring_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let AuthoringActionGoal = require('./AuthoringActionGoal.js');
let AuthoringActionResult = require('./AuthoringActionResult.js');
let AuthoringActionFeedback = require('./AuthoringActionFeedback.js');

//-----------------------------------------------------------

class AuthoringAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new AuthoringActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new AuthoringActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new AuthoringActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type AuthoringAction
    // Serialize message field [action_goal]
    bufferOffset = AuthoringActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = AuthoringActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = AuthoringActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type AuthoringAction
    let len;
    let data = new AuthoringAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = AuthoringActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = AuthoringActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = AuthoringActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += AuthoringActionGoal.getMessageSize(object.action_goal);
    length += AuthoringActionResult.getMessageSize(object.action_result);
    length += AuthoringActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'authoring_msgs/AuthoringAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '77d42cd79ed7af67d7aec4191f656d1c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    AuthoringActionGoal action_goal
    AuthoringActionResult action_result
    AuthoringActionFeedback action_feedback
    
    ================================================================================
    MSG: authoring_msgs/AuthoringActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    AuthoringGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: authoring_msgs/AuthoringGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    authoring_msgs/Action goal
    
    ================================================================================
    MSG: authoring_msgs/Action
    #Types
    uint8 PICK=0
    uint8 SCREW=1
    uint8 PLACE=2
    uint8 WIPE=3
    uint8 MOVE_OBJECT=4
    uint8 RESET=5
    uint8 MOVE=6
    uint8 MOVE_TO_CONTACT=7
    uint8 GRASP=8
    uint8 RELEASE=9
    uint8 VIEW=10
    uint8 INSPECT=11
    uint8 WAIT=12
    uint8 PUSH=13
    uint8 STOP=14
    uint8 INSERT=15
    uint8 MOVE_FORCE=16
    uint8 UNSCREW=17
    uint8 MOVE_ANGLE=18
    uint8 PULL=19
    uint8 CAMERA_VELOCITY=20
    uint8 MOVE_UNKNOWN=21
    uint8 PULL_DRAWER=22
    uint8 BIAS_FORCES=23
    uint8 DROP=24
    uint8 RELEASE_FORCE=25
    
    # Type
    uint8 type
    
    std_msgs/Bool sim
    
    std_msgs/Bool finished
    
    # HybridPoseArray (for high level planning)
    panda_ros_msgs/HybridPoseArray poses
    
    # HybridPose (for low level planning)
    panda_ros_msgs/HybridPose pose
    
    # JointState (for going to fixed position, example reset)
    float64[] joint_pose
    
    # Item
    std_msgs/String item
    
    # Velocity
    geometry_msgs/Twist velocity
    
    ================================================================================
    MSG: std_msgs/Bool
    bool data
    ================================================================================
    MSG: panda_ros_msgs/HybridPoseArray
    Header header
    panda_ros_msgs/HybridPose[] poses
    
    ================================================================================
    MSG: panda_ros_msgs/HybridPose
    # Pose
    geometry_msgs/Pose pose
    
    # Selection vector [6 (drop rotation for now)]
    uint8[] sel_vector
    
    # Desired Wrench
    geometry_msgs/Wrench wrench
    
    # Constraint Frame (might drop)
    geometry_msgs/Quaternion constraint_frame
    
    # Header
    Header header
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    ================================================================================
    MSG: geometry_msgs/Wrench
    # This represents force in free space, separated into
    # its linear and angular parts.
    Vector3  force
    Vector3  torque
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    ================================================================================
    MSG: std_msgs/String
    string data
    
    ================================================================================
    MSG: geometry_msgs/Twist
    # This expresses velocity in free space broken into its linear and angular parts.
    Vector3  linear
    Vector3  angular
    
    ================================================================================
    MSG: authoring_msgs/AuthoringActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    AuthoringResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: authoring_msgs/AuthoringResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    std_msgs/Bool success
    
    ================================================================================
    MSG: authoring_msgs/AuthoringActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    AuthoringFeedback feedback
    
    ================================================================================
    MSG: authoring_msgs/AuthoringFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    int32[] progress
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new AuthoringAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = AuthoringActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new AuthoringActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = AuthoringActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new AuthoringActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = AuthoringActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new AuthoringActionFeedback()
    }

    return resolved;
    }
};

module.exports = AuthoringAction;
