// Generated by gencpp from file panda_ros_msgs/JointPose.msg
// DO NOT EDIT!


#ifndef PANDA_ROS_MSGS_MESSAGE_JOINTPOSE_H
#define PANDA_ROS_MSGS_MESSAGE_JOINTPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace panda_ros_msgs
{
template <class ContainerAllocator>
struct JointPose_
{
  typedef JointPose_<ContainerAllocator> Type;

  JointPose_()
    : header()
    , joint_pose()  {
    }
  JointPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , joint_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_pose_type;
  _joint_pose_type joint_pose;





  typedef boost::shared_ptr< ::panda_ros_msgs::JointPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_ros_msgs::JointPose_<ContainerAllocator> const> ConstPtr;

}; // struct JointPose_

typedef ::panda_ros_msgs::JointPose_<std::allocator<void> > JointPose;

typedef boost::shared_ptr< ::panda_ros_msgs::JointPose > JointPosePtr;
typedef boost::shared_ptr< ::panda_ros_msgs::JointPose const> JointPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_ros_msgs::JointPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_ros_msgs::JointPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_ros_msgs::JointPose_<ContainerAllocator1> & lhs, const ::panda_ros_msgs::JointPose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.joint_pose == rhs.joint_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_ros_msgs::JointPose_<ContainerAllocator1> & lhs, const ::panda_ros_msgs::JointPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_ros_msgs::JointPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_ros_msgs::JointPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_ros_msgs::JointPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_ros_msgs::JointPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_ros_msgs::JointPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_ros_msgs::JointPose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_ros_msgs::JointPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "111f415c2656730dedd8594187f1259b";
  }

  static const char* value(const ::panda_ros_msgs::JointPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x111f415c2656730dULL;
  static const uint64_t static_value2 = 0xedd8594187f1259bULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_ros_msgs::JointPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_ros_msgs/JointPose";
  }

  static const char* value(const ::panda_ros_msgs::JointPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_ros_msgs::JointPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header\n"
"Header header\n"
"\n"
"# Velocities\n"
"float64[] joint_pose\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::panda_ros_msgs::JointPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_ros_msgs::JointPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.joint_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_ros_msgs::JointPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_ros_msgs::JointPose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joint_pose[]" << std::endl;
    for (size_t i = 0; i < v.joint_pose.size(); ++i)
    {
      s << indent << "  joint_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_ROS_MSGS_MESSAGE_JOINTPOSE_H
