// Generated by gencpp from file panda_ros_msgs/VelocityBoundPath.msg
// DO NOT EDIT!


#ifndef PANDA_ROS_MSGS_MESSAGE_VELOCITYBOUNDPATH_H
#define PANDA_ROS_MSGS_MESSAGE_VELOCITYBOUNDPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace panda_ros_msgs
{
template <class ContainerAllocator>
struct VelocityBoundPath_
{
  typedef VelocityBoundPath_<ContainerAllocator> Type;

  VelocityBoundPath_()
    : poses()
    , maxV(0.0)  {
    }
  VelocityBoundPath_(const ContainerAllocator& _alloc)
    : poses(_alloc)
    , maxV(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _poses_type;
  _poses_type poses;

   typedef double _maxV_type;
  _maxV_type maxV;





  typedef boost::shared_ptr< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityBoundPath_

typedef ::panda_ros_msgs::VelocityBoundPath_<std::allocator<void> > VelocityBoundPath;

typedef boost::shared_ptr< ::panda_ros_msgs::VelocityBoundPath > VelocityBoundPathPtr;
typedef boost::shared_ptr< ::panda_ros_msgs::VelocityBoundPath const> VelocityBoundPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator1> & lhs, const ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator2> & rhs)
{
  return lhs.poses == rhs.poses &&
    lhs.maxV == rhs.maxV;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator1> & lhs, const ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "009d80e152c59dacd396e7d157b35990";
  }

  static const char* value(const ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x009d80e152c59dacULL;
  static const uint64_t static_value2 = 0xd396e7d157b35990ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_ros_msgs/VelocityBoundPath";
  }

  static const char* value(const ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose[] poses\n"
"float64 maxV\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses);
      stream.next(m.maxV);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityBoundPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_ros_msgs::VelocityBoundPath_<ContainerAllocator>& v)
  {
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
    s << indent << "maxV: ";
    Printer<double>::stream(s, indent + "  ", v.maxV);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_ROS_MSGS_MESSAGE_VELOCITYBOUNDPATH_H
